# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts1', to='snippets.Contact')),
            ],
        ),
    ]
