# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171211_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
