# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20171211_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attribute_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attribute_value',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
