# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20171130_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
